@startuml
!pragma layout smetana

    class "Cliente" {
        - RUT
        - Membresía
    }

    class "Función" {
        - Código
        - Nombre
        - Horario
        - Precio
    }

    class "Sistema de Gestión" {
        - Lista de Funciones
        - Lista de Usuarios
    }

    "Sistema de Gestión" "Registra venta" o-- "Cliente"
    "Sistema de Gestión" o-- "Función"

@enduml